const JSZip = require('../../web/vendor/jszip/jszip.min.js'); const fs = require('fs');
const W = 'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"';
const rp = (extra = '') => `<w:rPr><w:rFonts w:ascii="Times New Roman" w:cs="Traditional Arabic"/>${extra}<w:sz w:val="28"/><w:szCs w:val="32"/></w:rPr>`;
const p = (text, ppr = '<w:bidi/><w:jc w:val="left"/>', extra = '') => `<w:p><w:pPr>${ppr}</w:pPr><w:r>${rp(extra)}<w:t xml:space="preserve">${text}</w:t></w:r></w:p>`;
const mathR = (t) => `<m:r><m:t>${t}</m:t></m:r>`;
let body = '';
body += `<w:p><w:pPr><w:pStyle w:val="Heading1"/><w:bidi/></w:pPr><w:r><w:t>اختبار الرياضيات للصف الثالث الثانوي</w:t></w:r></w:p>`;
body += p('الاسم: ...........................   التاريخ: ................', '<w:bidi/><w:jc w:val="left"/>');
body += p('السؤال الأول: اختر الإجابة الصحيحة فيما يلي:', '<w:bidi/><w:jc w:val="left"/><w:keepNext/>', '<w:bCs/><w:b/>');
for (let i = 0; i < 4; i++) body += `<w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="2"/></w:numPr><w:bidi/></w:pPr><w:r>${rp()}<w:t>الخيار رقم ${i + 1} من الأسئلة المتعددة</w:t></w:r></w:p>`;
body += `<w:p><w:pPr><w:bidi/><w:jc w:val="center"/></w:pPr><m:oMathPara><m:oMath><m:r><m:t>x=</m:t></m:r><m:f><m:num>${mathR('-b±')}<m:rad><m:radPr><m:degHide m:val="1"/></m:radPr><m:deg/><m:e><m:sSup><m:e>${mathR('b')}</m:e><m:sup>${mathR('2')}</m:sup></m:sSup>${mathR('-4ac')}</m:e></m:rad></m:num><m:den>${mathR('2a')}</m:den></m:f></m:oMath></m:oMathPara></w:p>`;
body += `<w:p><w:pPr><w:bidi/></w:pPr><w:r>${rp()}<w:t xml:space="preserve">نص عادي يحتوي على معادلة داخل السطر </w:t></w:r><m:oMath><m:sSub><m:e>${mathR('a')}</m:e><m:sub>${mathR('n')}</m:sub></m:sSub>${mathR('=')}<m:nary><m:naryPr><m:chr m:val="∑"/></m:naryPr><m:sub>${mathR('k=1')}</m:sub><m:sup>${mathR('n')}</m:sup><m:e>${mathR('k')}</m:e></m:nary></m:oMath><w:r>${rp()}<w:t xml:space="preserve"> ثم يكمل الجملة بعدها.</w:t></w:r></w:p>`;
// table with merged cells, RTL
const cell = (t, span = 1, fill = '', vm = '') => `<w:tc><w:tcPr><w:tcW w:w="2000" w:type="dxa"/>${span > 1 ? `<w:gridSpan w:val="${span}"/>` : ''}${vm}${fill ? `<w:shd w:val="clear" w:fill="${fill}"/>` : ''}</w:tcPr>${p(t, '<w:bidi/><w:jc w:val="center"/>')}</w:tc>`;
body += `<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/><w:tblW w:w="6000" w:type="dxa"/><w:bidiVisual/></w:tblPr><w:tblGrid><w:gridCol w:w="2000"/><w:gridCol w:w="2000"/><w:gridCol w:w="2000"/></w:tblGrid>
<w:tr>${cell('الجدول الأول', 3, 'D9E2F3')}</w:tr><w:tr>${cell('أ', 1, '', '<w:vMerge w:val="restart"/>')}${cell('ب')}${cell('ج')}</w:tr><w:tr>${cell('', 1, '', '<w:vMerge/>')}${cell('1')}${cell('2')}</w:tr></w:tbl>`;
for (let i = 0; i < 70; i++) body += p(`الفقرة رقم ${i + 1}: هذا نص عربي طويل نسبياً لاختبار تقسيم الصفحات والتفاف الأسطر والمحاذاة من اليمين إلى اليسار، ويتضمن English words mixed inside and numbers ${i * 7}.`, '<w:bidi/><w:jc w:val="both"/><w:spacing w:after="120"/>');
body += `<w:p><w:r><w:br w:type="page"/></w:r></w:p>` + p('صفحة بعد فاصل الصفحة الصريح.', '<w:bidi/>');
body += `<w:sectPr><w:headerReference w:type="default" r:id="rId9"/><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="708" w:footer="708" w:gutter="0"/></w:sectPr>`;
const z = new JSZip();
z.file('[Content_Types].xml', `<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`);
z.file('_rels/.rels', `<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`);
z.file('word/_rels/document.xml.rels', `<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId9" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Target="header1.xml"/></Relationships>`);
z.file('word/header1.xml', `<?xml version="1.0"?><w:hdr ${W}><w:p><w:pPr><w:bidi/><w:jc w:val="center"/></w:pPr><w:r><w:t xml:space="preserve">مدرسة النور — صفحة </w:t></w:r><w:fldSimple w:instr=" PAGE "><w:r><w:t>1</w:t></w:r></w:fldSimple></w:p></w:hdr>`);
z.file('word/styles.xml', `<?xml version="1.0"?><w:styles ${W}><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Times New Roman" w:cs="Traditional Arabic"/><w:sz w:val="24"/><w:szCs w:val="28"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="100" w:line="276" w:lineRule="auto"/></w:pPr></w:pPrDefault></w:docDefaults>
<w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style>
<w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:pPr><w:keepNext/><w:jc w:val="center"/><w:spacing w:before="240" w:after="200"/></w:pPr><w:rPr><w:b/><w:bCs/><w:color w:val="1F3864"/><w:sz w:val="36"/><w:szCs w:val="40"/></w:rPr></w:style>
<w:style w:type="table" w:styleId="TableGrid"><w:name w:val="Table Grid"/><w:tblPr><w:tblBorders><w:top w:val="single" w:sz="6" w:color="000000"/><w:left w:val="single" w:sz="6" w:color="000000"/><w:bottom w:val="single" w:sz="6" w:color="000000"/><w:right w:val="single" w:sz="6" w:color="000000"/><w:insideH w:val="single" w:sz="6" w:color="000000"/><w:insideV w:val="single" w:sz="6" w:color="000000"/></w:tblBorders></w:tblPr></w:style></w:styles>`);
z.file('word/numbering.xml', `<?xml version="1.0"?><w:numbering ${W}><w:abstractNum w:abstractNumId="1"><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="arabicAbjad"/><w:lvlText w:val="%1)"/><w:pPr><w:ind w:left="720" w:hanging="360"/></w:pPr></w:lvl></w:abstractNum><w:num w:numId="2"><w:abstractNumId w:val="1"/></w:num></w:numbering>`);
z.file('word/document.xml', `<?xml version="1.0" encoding="UTF-8"?><w:document ${W}><w:body>${body}</w:body></w:document>`);
z.generateAsync({ type: 'nodebuffer' }).then(b => { fs.writeFileSync('fx/exam.docx', b); console.log('docx', b.length); });
